name: Run static analysis

on:
  push:
    branches: [ trunk, pending, staging-* ]
  pull_request:
    branches: [ trunk, pending, staging-* ]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cppcheck
      run: sudo apt install -y cppcheck
    - name: Run cppcheck
      run: cppcheck --error-exitcode=1 -j 2 --suppressions-list=.github/files/supressions_list.txt feeds/wlan-ap/opensync/src
